[workspace]
members = [
	"frame/evm/precompile/call-vm",
	"frame/vm-bridge",
	"frame/rgrandpa",
	"frame/esbind",
#	"frame/upgrade-test",
	"node/phoenix",
#	"runtime/cycan",
	"runtime/phoenix",
]

[profile.release]
panic = "unwind"

