[workspace]
members = [
#	"frame/evm/precompile/call-vm",
#	"frame/vm-bridge",
#	"frame/rgrandpa",
#	"frame/esbind",
#	"frame/upgrade-test",
	"primitives",
	"node/phoenix",
	"runtime/phoenix",
]

[profile.release]
panic = "unwind"

